version: '1.0'

services:

  app:
    image: spring-boot-docker
    ports:
      - 8181:8080
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345